# Generated by Django 4.1.5 on 2023-03-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20201007_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='pollo.png', upload_to=''),
        ),
    ]
