# Generated by Django 4.1.5 on 2023-03-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_post_image_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=False, max_length=15),
            preserve_default=False,
        ),
    ]
