# Generated by Django 4.1.5 on 2023-03-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
    ]
