# Generated by Django 4.1.5 on 2023-03-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
